#!/usr/bin/python3

import sys
from vyos.template import get_ipv6_link_local

if __name__ == '__main__':
    if len(sys.argv)>1:
        addr = sys.argv[1]
        if addr not in get_ipv6_link_local():
            sys.exit(1)

    sys.exit(0)
